#.travis.yml

language: node_js
node_js:
  - '8.12.0'

branches:
  only:
    - master

before_script:
  - npm install --save-dev @angular/cli@latest
  - npm install

script:
  - ng build --prod

after_success:
  - find . -type d \( -path "./dist/.*" -o -path "./node_modules" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://ftp.moraisandre.com/taxaenjoei.moraisandre.com/ --user ${SFTP_USER}:${SFTP_PASSWORD} \;
